name: cookbook-geosat
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - xarray
  - satpy
  - matplotlib
  - pandas
  - pip:
    - pip install --upgrade nbclient